# Generated by Django 2.2.2 on 2019-08-02 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeName', models.CharField(max_length=64)),
                ('CodeLink', models.URLField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetupName', models.CharField(max_length=64)),
                ('meetupDescription', models.TextField()),
                ('meetupLocation', models.TextField()),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteName', models.CharField(max_length=64)),
                ('NoteLink', models.URLField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('roleDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=64)),
                ('slideLink', models.URLField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='speaker/')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorName', models.CharField(max_length=64)),
                ('sponsorLink', models.URLField(max_length=2048)),
                ('sponsorLogo', models.ImageField(upload_to='sponsor/')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('role_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talkName', models.CharField(max_length=64)),
                ('talkStatus', models.IntegerField(choices=[(0, 'onSite'), (1, 'onLine')], default=0)),
                ('talkDescription', models.TextField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('codeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Code_details', to='web_app.Code')),
                ('meetupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meetup_details', to='web_app.Meetup')),
                ('noteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notebook_details', to='web_app.Notebook')),
                ('slideId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_details', to='web_app.Slide')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('githubLink', models.URLField(blank=True, max_length=2048, unique=True)),
                ('kaggleLink', models.URLField(blank=True, max_length=2048, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='volunteer/')),
                ('vol_status', models.IntegerField(choices=[(0, 'deactive'), (1, 'active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TalkRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('requirementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_details_for_TalkRequirement', to='web_app.Requirement')),
                ('talkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_details_for_TalkRequirement', to='web_app.Talk')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirementTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirementType_details', to='web_app.RequirementType'),
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Partcipate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField(blank=True)),
                ('speakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_details_for_partcipate', to='web_app.Speaker')),
                ('talkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_details_for_Speaker_Partcipate', to='web_app.Talk')),
            ],
        ),
        migrations.CreateModel(
            name='HasSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_details', to='web_app.Meetup')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorrole_details', to='web_app.SponsorRole')),
                ('sponsorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_details', to='web_app.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='HasRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_details', to='web_app.Role')),
                ('volunteerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_details', to='web_app.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='FollowSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMediaHandleName', models.CharField(max_length=64)),
                ('smhLink', models.URLField(max_length=2048)),
                ('speakerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_details_for_follow_speaker', to='web_app.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Engaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('hasRoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_role_detail', to='web_app.HasRole')),
                ('talkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_details_for_Volunteer_Engaged', to='web_app.Talk')),
            ],
        ),
    ]
