# Generated by Django 2.2.3 on 2019-07-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talk', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('Linkedin', models.TextField()),
                ('kaggle', models.TextField()),
                ('github', models.TextField()),
                ('slide', models.TextField()),
                ('Notebook', models.TextField()),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('time', models.TimeField()),
                ('talk', models.CharField(max_length=100)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web_app.speaker')),
            ],
        ),
    ]
