# Generated by Django 2.2.3 on 2019-07-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='program',
        ),
        migrations.DeleteModel(
            name='speaker',
        ),
    ]
