# Generated by Django 2.2.3 on 2019-07-29 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_app', '0002_auto_20190729_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_time', models.CharField(max_length=10)),
                ('talk', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talk', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('Linkedin', models.TextField()),
                ('kaggle', models.TextField()),
                ('github', models.TextField()),
                ('slide', models.TextField()),
                ('Notebook', models.TextField()),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
