# Generated by Django 2.2.3 on 2019-07-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_pastspeakers_sponsors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pastspeakers',
        ),
        migrations.DeleteModel(
            name='program',
        ),
        migrations.DeleteModel(
            name='speaker',
        ),
        migrations.DeleteModel(
            name='sponsors',
        ),
    ]
