# Generated by Django 2.2.3 on 2019-07-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_pastspeakers_program_speaker_sponsors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pastspeakers',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='sponsors',
        ),
    ]
