# Generated by Django 2.2.3 on 2019-07-30 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_app', '0007_auto_20190730_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='pastspeakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talk', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('images', models.ImageField(upload_to='images/')),
                ('Linkedin', models.TextField()),
                ('kaggle', models.TextField()),
                ('github', models.TextField()),
                ('slide', models.TextField()),
                ('Notebook', models.TextField()),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_time', models.CharField(max_length=10)),
                ('talk', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('talk', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('Linkedin', models.TextField()),
                ('kaggle', models.TextField()),
                ('github', models.TextField()),
                ('slide', models.TextField()),
                ('Notebook', models.TextField()),
                ('code', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('sponsorlink', models.TextField()),
            ],
        ),
    ]
